repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.1
    hooks:
      - id: yamlfmt
        files: '^files/deploymentfiles/.*\.(yaml|yml)$'
        exclude: '(?i)^(.*\.md|.*\.txt|.*\.rb|.*\.conf|.*\.cfg)$'
        args: ["--check"]  # Use --check flag to report issues without making changes
        stages: [commit]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args:
          - --strict
        additional_dependencies:
          - yamllint
        files: '^files/deploymentfiles/.*\.(yaml|yml)$'
        exclude: '(?i)^(.*\.md|.*\.txt|.*\.rb|.*\.conf|.*\.cfg)$'
        stages: [commit]

