groups:
  - name: cpu_alert
    rules:
      - alert: cpu_threshold
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle", job=~"prometheus"}[5m])) * 100) > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: CPU Utilization is more than the threshold which is 90
          description: CPU Utilization is more than the threshold for the instance {{$labels.instance}}
