groups:
- name: disk_alert_issue
  rules:
  - alert: disk_threshold
    expr:  (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Disk Utilization for {{$labels.mountpoint}} is more than the threshold 90%. Usage is {{ $value }} %"
      description: "Disk Utilization  {{$labels.mountpoint}} partition is more than the threshold for the instance {{$labels.instance}}"
