groups:
- name: disk_alert
  rules:
  - alert: disk_threshold
    expr:  ((node_filesystem_size_bytes{ fstype="ext4"} - node_filesystem_avail_bytes{ fstype="ext4"}) / node_filesystem_size_bytes{ fstype="ext4"}) * 100  > 90
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Disk Utilization for {{$labels.mountpoint}} is more than the threshold 90%. Usage is {{ $value }} %"
      description: "Disk Utilization  {{$labels.mountpoint}} partition is more than the threshold for the instance {{$labels.instance}}"
