groups:
- name: alert-prometheus-target-missing
  rules:
  - alert: PrometheusTargetMissing
    expr: up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'Prometheus target missing (instance {{ $labels.instance }})'
      summary: 'A Prometheus target has disappeared. An exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}'
